import { Inter } from "next/font/google";
import "./globals.css";
import { AppBar, Box, IconButton, Toolbar } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Github Users API",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="manifest" href="manifest.webmanifest" />
      {/* <script async src="https://cdn.jsdelivr.net/npm/pwacompat" crossOrigin="anonymous"></script> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
